#!/usr/bin/env python3
"""Regenerate terms.html's body from the app's canonical terms text.

The terms used to be maintained by hand in three places -- two app screens and
this website -- and all three drifted apart. The app now keeps one copy in
`lib/legal/kukatu_terms.dart`; this script renders that same copy into
terms.html so the published page cannot fall behind the shipped app.

Usage:
    python3 tools/build_terms.py [path/to/kukatu_terms.dart]

Writes terms.html in place and prints the effective date it published.
"""

from __future__ import annotations

import html
import pathlib
import re
import sys

DEFAULT_DART = pathlib.Path(
    "/Users/sky/Documents/GitHub/Bookclub-release/project_0"
    "/lib/legal/kukatu_terms.dart"
)
TERMS_HTML = pathlib.Path(__file__).resolve().parent.parent / "terms.html"

START = "<!-- BEGIN GENERATED TERMS -->"
END = "<!-- END GENERATED TERMS -->"

STRING = re.compile(r'"((?:[^"\\]|\\.)*)"', re.S)


def unescape(raw: str) -> str:
    return (
        raw.replace("\\n", "\n").replace('\\"', '"').replace("\\\\", "\\")
    )


def parse_sections(dart: str) -> tuple[str, list[tuple[str, str]]]:
    updated = re.search(
        r'const String kukatuTermsLastUpdated\s*=\s*"([^"]*)"', dart
    )
    if not updated:
        raise SystemExit("could not find kukatuTermsLastUpdated")
    last_updated = updated.group(1)

    start = dart.index("kukatuTermsSections = [")
    body = dart[start:]
    # Records look like:  ( title: "...", body: "..." "...", ),
    records = re.findall(r"\(\s*title:(.*?),\s*\)", body, re.S)
    if not records:
        raise SystemExit("could not find any sections")

    sections: list[tuple[str, str]] = []
    for record in records:
        if "body:" not in record:
            raise SystemExit(f"section without a body: {record[:60]!r}")
        title_src, body_src = record.split("body:", 1)
        title = "".join(unescape(m) for m in STRING.findall(title_src))
        text = "".join(unescape(m) for m in STRING.findall(body_src))
        text = text.replace("$kukatuTermsLastUpdated", last_updated)
        sections.append((title.strip(), text))
    return last_updated, sections


def render_block(block: str) -> str:
    lines = [line for line in block.split("\n") if line.strip()]
    if lines and all(line.lstrip().startswith("• ") for line in lines):
        items = "\n".join(
            f"            <li>{html.escape(line.lstrip()[2:].strip())}</li>"
            for line in lines
        )
        return f"        <ul>\n{items}\n        </ul>"
    joined = "<br>\n        ".join(html.escape(line.strip()) for line in lines)
    return f"        <p>{joined}</p>"


def render(last_updated: str, sections: list[tuple[str, str]]) -> str:
    out: list[str] = [
        "        <!-- Generated by tools/build_terms.py from the app's",
        "             lib/legal/kukatu_terms.dart. Do not edit by hand:",
        "             change the app's copy and re-run the script. -->",
        '        <div class="last-updated">',
        f"            Last updated: {html.escape(last_updated)}",
        "        </div>",
        "",
    ]
    for title, body in sections:
        # The closing contact section keeps the page's callout styling.
        contact = title.lower().endswith("contact")
        if contact:
            out.append('        <div class="contact-box">')
        if title:
            out.append(f"        <h2>{html.escape(title)}</h2>")
        blocks = [b for b in body.split("\n\n") if b.strip()]
        # The opening section repeats the date the banner above already shows.
        if not title:
            blocks = [
                b for b in blocks if not b.strip().startswith("Last updated:")
            ]
        out.extend(render_block(block) for block in blocks)
        if contact:
            out.append("        </div>")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    dart_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DART
    last_updated, sections = parse_sections(
        dart_path.read_text(encoding="utf-8")
    )

    page = TERMS_HTML.read_text(encoding="utf-8")
    if START not in page or END not in page:
        raise SystemExit(
            f"terms.html is missing the {START} / {END} markers; add them "
            "around the generated region first"
        )
    head, rest = page.split(START, 1)
    _, tail = rest.split(END, 1)
    page = f"{head}{START}\n{render(last_updated, sections)}{END}{tail}"
    TERMS_HTML.write_text(page, encoding="utf-8")
    print(f"terms.html regenerated: {len(sections)} sections, {last_updated}")


if __name__ == "__main__":
    main()
